"""audit et taches

Revision ID: 3aa17d42bb16
Revises: 552f4e486f97
Create Date: 2026-09-22 16:00:40.966437

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from jurismind.core.config import get_settings
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa17d42bb16'
down_revision: Union[str, Sequence[str], None] = '552f4e486f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('parametres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statut', sa.Enum('en_attente', 'en_cours', 'terminee', 'echec', name='statut_tache', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('executer_apres', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taches'))
    )
    op.create_index('ix_taches_a_faire', 'taches', ['statut', 'executer_apres'], unique=False)
    op.create_table('journal_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_journal_audit_utilisateur_id_utilisateurs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_audit'))
    )
    op.create_index(op.f('ix_journal_audit_dossier_id'), 'journal_audit', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_journal_audit_utilisateur_id'), 'journal_audit', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###

    # Le journal d'audit : on n'y écrit qu'en ajout, et on n'y lit que ce qu'on a le droit de lire.
    role = get_settings().postgres_app_user
    op.execute(f"REVOKE UPDATE, DELETE, TRUNCATE ON journal_audit FROM {role}")
    op.execute("ALTER TABLE journal_audit ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY ecriture ON journal_audit FOR INSERT "
        "WITH CHECK (utilisateur_id = utilisateur_courant())"
    )
    op.execute(
        "CREATE POLICY lecture ON journal_audit FOR SELECT "
        "USING (role_courant() = 'admin' OR utilisateur_id = utilisateur_courant())"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS lecture ON journal_audit")
    op.execute("DROP POLICY IF EXISTS ecriture ON journal_audit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_audit_utilisateur_id'), table_name='journal_audit')
    op.drop_index(op.f('ix_journal_audit_dossier_id'), table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_index('ix_taches_a_faire', table_name='taches')
    op.drop_table('taches')
    # ### end Alembic commands ###
