"""alias des clients en double

Revision ID: 56caf9e03757
Revises: 3aa17d42bb16
Create Date: 2026-09-28 18:34:03.967263

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56caf9e03757"
down_revision: Union[str, Sequence[str], None] = "3aa17d42bb16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alias_clients",
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["clients.id"], name=op.f("fk_alias_clients_client_id_clients"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("external_id", name=op.f("pk_alias_clients")),
    )
    op.create_index(op.f("ix_alias_clients_client_id"), "alias_clients", ["client_id"], unique=False)
    # ### end Alembic commands ###

    # Table technique : invisible depuis l'application (RLS activée sans aucune règle).
    op.execute("ALTER TABLE alias_clients ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alias_clients_client_id"), table_name="alias_clients")
    op.drop_table("alias_clients")
    # ### end Alembic commands ###
