"""propositions de l'agent de tri

Revision ID: c16a3fc527c6
Revises: e0cb9175f8de
Create Date: 2026-10-06 19:14:32.504206

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c16a3fc527c6'
down_revision: Union[str, Sequence[str], None] = 'e0cb9175f8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crée la table des propositions et l'isolation qui va avec."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('rattachement', 'brouillon', 'tache_crm', name='type_proposition', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('statut', sa.Enum('proposee', 'validee', 'appliquee', 'rejetee', 'echouee', name='statut_proposition', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('communication_id', sa.Integer(), nullable=True),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('justification', sa.String(length=500), nullable=False),
    sa.Column('confiance', sa.Enum('haute', 'moyenne', 'faible', name='confiance_proposition', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decide_par_id', sa.Integer(), nullable=True),
    sa.Column('decide_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_propositions_client_id_clients')),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], name=op.f('fk_propositions_communication_id_communications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decide_par_id'], ['utilisateurs.id'], name=op.f('fk_propositions_decide_par_id_utilisateurs')),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_propositions_dossier_id_dossiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_propositions'))
    )
    op.create_index(op.f('ix_propositions_communication_id'), 'propositions', ['communication_id'], unique=False)
    op.create_index(op.f('ix_propositions_dossier_id'), 'propositions', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_propositions_statut'), 'propositions', ['statut'], unique=False)
    # ### end Alembic commands ###

    # Écrit à la main : l'isolation suit celle des échanges à trier. Une proposition qui
    # vise un dossier n'est visible que de ceux qui voient ce dossier ; une proposition
    # sans dossier (un prospect qui demande un rendez-vous) est visible du cabinet.
    op.execute("ALTER TABLE propositions ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY isolation ON propositions USING (
            dossier_id IN (SELECT dossiers_autorises())
            OR (dossier_id IS NULL AND role_courant() IN ('avocat', 'assistant'))
        )
    """)


def downgrade() -> None:
    """Supprime la table des propositions."""
    op.execute("DROP POLICY IF EXISTS isolation ON propositions")
    op.execute("ALTER TABLE propositions DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propositions_statut'), table_name='propositions')
    op.drop_index(op.f('ix_propositions_dossier_id'), table_name='propositions')
    op.drop_index(op.f('ix_propositions_communication_id'), table_name='propositions')
    op.drop_table('propositions')
    # ### end Alembic commands ###
