"""elements du CRM

Revision ID: c2dbd772e8f2
Revises: 56caf9e03757
Create Date: 2026-09-28 19:51:43.603012

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2dbd772e8f2'
down_revision: Union[str, Sequence[str], None] = '56caf9e03757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements_crm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('opportunite', 'activite', 'tache', name='type_element_crm', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('date_element', sa.Date(), nullable=True),
    sa.Column('montant_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('statut', sa.String(length=40), nullable=True),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('donnees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_elements_crm_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elements_crm')),
    sa.UniqueConstraint('external_id', name=op.f('uq_elements_crm_external_id'))
    )
    op.create_index(op.f('ix_elements_crm_client_id'), 'elements_crm', ['client_id'], unique=False)
    op.add_column('clients', sa.Column('crm_id', sa.String(length=40), nullable=True))
    op.create_unique_constraint(op.f('uq_clients_crm_id'), 'clients', ['crm_id'])
    # ### end Alembic commands ###

    # Un élément du CRM est visible si son client l'est (lui-même visible via ses dossiers).
    op.execute("ALTER TABLE elements_crm ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY isolation ON elements_crm USING (client_id IN (SELECT id FROM clients))")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS isolation ON elements_crm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_clients_crm_id'), 'clients', type_='unique')
    op.drop_column('clients', 'crm_id')
    op.drop_index(op.f('ix_elements_crm_client_id'), table_name='elements_crm')
    op.drop_table('elements_crm')
    # ### end Alembic commands ###
