"""tables initiales

Revision ID: d67875560077
Revises: 
Create Date: 2026-09-22 14:15:06.517879

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd67875560077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('societe', 'particulier', name='type_client', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('forme_juridique', sa.String(length=20), nullable=True),
    sa.Column('rccm', sa.String(length=40), nullable=True),
    sa.Column('ninea', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=250), nullable=True),
    sa.Column('ville', sa.String(length=60), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('external_id', name=op.f('uq_clients_external_id'))
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'avocat', 'assistant', name='role', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utilisateurs')),
    sa.UniqueConstraint('email', name=op.f('uq_utilisateurs_email')),
    sa.UniqueConstraint('external_id', name=op.f('uq_utilisateurs_external_id'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=60), nullable=True),
    sa.Column('nom', sa.String(length=60), nullable=False),
    sa.Column('fonction', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_contacts_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('external_id', name=op.f('uq_contacts_external_id'))
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Enum('contentieux', 'conseil', name='type_dossier', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('matiere', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.Enum('en_cours', 'clos', 'archive', name='statut_dossier', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('date_ouverture', sa.Date(), nullable=False),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('juridiction', sa.String(length=150), nullable=True),
    sa.Column('numero_rg', sa.String(length=40), nullable=True),
    sa.Column('enjeu_fcfa', sa.BigInteger(), nullable=True),
    sa.Column('confidentiel', sa.Boolean(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_dossiers_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossiers')),
    sa.UniqueConstraint('external_id', name=op.f('uq_dossiers_external_id')),
    sa.UniqueConstraint('reference', name=op.f('uq_dossiers_reference'))
    )
    op.create_index(op.f('ix_dossiers_client_id'), 'dossiers', ['client_id'], unique=False)
    op.create_table('acces_dossiers',
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('est_responsable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_acces_dossiers_dossier_id_dossiers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('fk_acces_dossiers_utilisateur_id_utilisateurs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dossier_id', 'utilisateur_id', name=op.f('pk_acces_dossiers'))
    )
    op.create_index(op.f('ix_acces_dossiers_utilisateur_id'), 'acces_dossiers', ['utilisateur_id'], unique=False)
    op.create_table('communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('email', 'courrier', 'telephone', name='canal', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('sens', sa.Enum('entrant', 'sortant', 'interne', name='sens_communication', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('date_echange', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expediteur', sa.String(length=255), nullable=False),
    sa.Column('destinataires', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('objet', sa.String(length=300), nullable=True),
    sa.Column('corps', sa.Text(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_communications_dossier_id_dossiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communications')),
    sa.UniqueConstraint('external_id', name=op.f('uq_communications_external_id'))
    )
    op.create_index(op.f('ix_communications_dossier_id'), 'communications', ['dossier_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('categorie_source', sa.String(length=40), nullable=True),
    sa.Column('categorie_detectee', sa.String(length=40), nullable=True),
    sa.Column('sens', sa.Enum('entrant', 'sortant', 'interne', name='sens_document', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('date_document', sa.Date(), nullable=True),
    sa.Column('auteur', sa.String(length=200), nullable=True),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('empreinte_sha256', sa.String(length=64), nullable=True),
    sa.Column('statut_traitement', sa.Enum('a_traiter', 'en_cours', 'traite', 'erreur', name='statut_traitement', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('ocr_utilise', sa.Boolean(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_documents_dossier_id_dossiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('external_id', name=op.f('uq_documents_external_id'))
    )
    op.create_index(op.f('ix_documents_dossier_id'), 'documents', ['dossier_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('qualite', sa.Enum('adverse', 'avocat_adverse', 'huissier', 'tiers', name='qualite_partie', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('adresse', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_parties_dossier_id_dossiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parties')),
    sa.UniqueConstraint('external_id', name=op.f('uq_parties_external_id'))
    )
    op.create_index(op.f('ix_parties_dossier_id'), 'parties', ['dossier_id'], unique=False)
    op.create_index(op.f('ix_parties_email'), 'parties', ['email'], unique=False)
    op.create_table('extraits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('communication_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('recherche_texte', postgresql.TSVECTOR(), sa.Computed("to_tsvector('french', contenu)", persisted=True), nullable=False),
    sa.Column('metadonnees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('(document_id IS NULL) <> (communication_id IS NULL)', name=op.f('ck_extraits_une_seule_source')),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], name=op.f('fk_extraits_communication_id_communications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extraits_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_extraits_dossier_id_dossiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraits'))
    )
    op.create_index(op.f('ix_extraits_communication_id'), 'extraits', ['communication_id'], unique=False)
    op.create_index(op.f('ix_extraits_document_id'), 'extraits', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraits_dossier_id'), 'extraits', ['dossier_id'], unique=False)
    op.create_index('ix_extraits_embedding', 'extraits', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_extraits_recherche_texte', 'extraits', ['recherche_texte'], unique=False, postgresql_using='gin')
    op.create_table('pieces_jointes',
    sa.Column('communication_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], name=op.f('fk_pieces_jointes_communication_id_communications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_pieces_jointes_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('communication_id', 'document_id', name=op.f('pk_pieces_jointes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_jointes')
    op.drop_index('ix_extraits_recherche_texte', table_name='extraits', postgresql_using='gin')
    op.drop_index('ix_extraits_embedding', table_name='extraits', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_extraits_dossier_id'), table_name='extraits')
    op.drop_index(op.f('ix_extraits_document_id'), table_name='extraits')
    op.drop_index(op.f('ix_extraits_communication_id'), table_name='extraits')
    op.drop_table('extraits')
    op.drop_index(op.f('ix_parties_email'), table_name='parties')
    op.drop_index(op.f('ix_parties_dossier_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_documents_dossier_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_communications_dossier_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_acces_dossiers_utilisateur_id'), table_name='acces_dossiers')
    op.drop_table('acces_dossiers')
    op.drop_index(op.f('ix_dossiers_client_id'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('utilisateurs')
    op.drop_table('clients')
    # ### end Alembic commands ###
