"""extractions structurees

Revision ID: e0cb9175f8de
Revises: 9ca6109f1b38
Create Date: 2026-09-29 20:24:36.558593

"""

from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0cb9175f8de"
down_revision: Union[str, Sequence[str], None] = "9ca6109f1b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("schema", sa.String(length=40), nullable=False),
        sa.Column("donnees", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("champs_douteux", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "statut",
            sa.Enum(
                "proposee",
                "validee",
                "rejetee",
                name="statut_extraction",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("modele", sa.String(length=60), nullable=True),
        sa.Column("valide_par_id", sa.Integer(), nullable=True),
        sa.Column("valide_le", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cree_le", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("modifie_le", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_extractions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["valide_par_id"], ["utilisateurs.id"], name=op.f("fk_extractions_valide_par_id_utilisateurs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractions")),
    )
    op.create_index(op.f("ix_extractions_document_id"), "extractions", ["document_id"], unique=False)
    # ### end Alembic commands ###

    # Une extraction est visible si son document l'est : l'isolation se propage.
    op.execute("ALTER TABLE extractions ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY isolation ON extractions USING (document_id IN (SELECT id FROM documents))")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS isolation ON extractions")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extractions_document_id"), table_name="extractions")
    op.drop_table("extractions")
    # ### end Alembic commands ###
